### ISSUE TITLE
Home Page Responsive Design

### ISSUE THREAD

**Issue by felicedeNigris** [felicedeNigris/MixtapeForum#7]
- [x] At 960px
- CENTER: remove the white triangles
- CENTER: change font color to white
- [x] At 640px
- TOP: remove width:50% from .intro-top. intro-text
- [x] At 450px
- TOP: change font-size to 32px
- CENTER: remove width: 33.33% from h2 tags
- CENTER: change font color to white and 18px
- BOTTOM: change font-size to 18px

**Comment by EricSSartorius** [comment]
I will see if I can knock this off today

**Comment by EricSSartorius** [comment]
@felicedeNigris When you say 'At' do you mean above or below?

**Comment by felicedeNigris** [comment]
Below
